name: Create Website

on:
  schedule:
    - cron: '00 14 * * *' # runs at 14:00 UTC everyday 16:00 local time

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      #- name: checkout repo content
        #uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the python version needed

      - name: install python packages
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
      - name: execute py script # run collectData.py to get the latest data
        run: sudo python ImpfungMS.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Pushes website to gitpages repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'website/ImpfQuoteMuenster.html'
          destination_repo: 'kickbutts/kickbutts.github.io'
          user_email: 'kickbutts@gmx.de'
          user_name: 'kickbutts'
          commit_message: 'newly generated website'
